version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Publish Release
          command: MAVEN_REPO_URL="https://api.bintray.com/maven/americanexpress/maven/com.americanexpress.unify.jdocs/;publish=0" mvn clean deploy --settings=".circle.settings.xml"
