version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - maven_central_credentials
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.322
    steps:
      - checkout
      - restore_cache:
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn --settings ".circleci/settings.xml" -B -DskipTests clean deploy -e -X
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unify-jdocs-{{ checksum "pom.xml" }}


