version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gradle

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config user.email "balraj.goel@aexp.com"
            git config user.name "Balraj Goel"
      - add_ssh_keys:
          fingerprints:
            - "55:4d:82:b5:74:a7:d6:ee:cf:d7:8a:48:09:7c:82:5d"
      - restore_cache:
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn install
      - run: mvn --settings ".circleci/settings.xml" -B release:clean release:prepare release:perform -P release


