version: 2.1

commands:
  configure-gpg:
    description: |
      Configure GPG private keys.
    steps:
      - run:
          command: echo $ORG_GRADLE_PROJECT_signingKey_base64 | base64 --decode | gpg --batch --no-tty --import --yes
          name: Configure GPG private key for signing project artifacts in OSS Sonatype

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - maven_central_credentials
            - code_signing_credentials
          filters:
            branches:
              only:
                - main

jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.322
    steps:
      - checkout
      - restore_cache:
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - configure-gpg
      - run: mvn --settings ".circleci/settings.xml" -B -DskipTests clean deploy
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unify-jdocs-{{ checksum "pom.xml" }}
