version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          context:
            - maven_central_credentials
            - code_signing_credentials
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run:
          name: Configure Git
          command: |
            git config user.email "balraj.goel@aexp.com"
            git config user.name "Balraj Goel"
      - add_ssh_keys:
          fingerprints:
            - "7e:49:45:c8:1f:b9:95:58:6c:a6:76:d8:93:7a:04:67"
      - restore_cache:
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache: # saves the project dependencies
          paths:
            - ~/.m2
          key: unify-jdocs-{{ checksum "pom.xml" }}
      - run: mvn install
      - run: mvn --settings ".circleci/settings.xml" -B release:clean release:prepare release:perform -P release


